config/routes.rb
Rails.application.routes.draw do
  # get 'bookings/create'
  devise_for :users

  root to: 'pages#home'
  resources :items do
    resources :bookings, only: :create
  end
  resources :bookings, only: :update

  get '/my_bookings', to: 'bookings#my_bookings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability_validator.rb
class AvailabilityValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    bookings = Booking.where(["item_id =?", record.item_id])
    date_ranges = bookings.map { |b| b.start_date..b.end_date }

    date_ranges.each do |range|
      if range.include? value
        record.errors.add(attribute, "not available")
      end
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :item
  # belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  belongs_to :renter, class_name: 'User', foreign_key: 'renter_id'

  # validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date

  def status_to_s
    if status.nil?
      "Pending"
    elsif status
      "Accepted"
    else
      "Declined"
    end
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :bookings
  belongs_to :user

  def unavailable_dates
   bookings.pluck(:start_date, :end_date).map do |range|
     { from: range[0], to: range[1] }
   end
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :bookings, foreign_key: :renter_id
  has_many :owner_bookings, through: :items, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @item = Item.find(params[:item_id])
    @booking.item = @item
    @booking.renter = current_user
    # @booking.owner = @item.user
    @booking.save!
    redirect_to item_path(@booking.item)
  end

  def my_bookings
    @my_bookings = current_user.owner_bookings
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:status].to_i.zero? ? false : true
    if @booking.save
      redirect_to my_bookings_path
    else
      render :my_bookings
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
    @bookings = @item.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/my_bookings.html.erb
<h1>My Owner Bookings</h1>

<% @my_bookings.each do |booking| %>
  <div class="container">
    <p>From: <%= booking.start_date %> To: <%= booking.end_date %></p>
    <p>Renter: <%= booking.renter.email %></p>
    <p>Status: <%= booking.status_to_s %></p>
    <%= button_to 'Accept', booking_path(booking),
                            method: 'patch', params: { status: 1 } %>
    <%= button_to 'Decline', booking_path(booking),
                            method: 'patch', params: { status: 0 } %>
  </div>

<% end %>

app/views/items/index.html.erb
<h1>All Items</h1>

<% @items.each do |item| %>
  <li><%= link_to item.name, item_path(item) %></li>
<% end %>

app/views/items/show.html.erb
<div class="container">
  <h1>Item name: <%= @item.name %></h1>
  <p>Price per day: $<span id="price">12</span></p>

  <p id="widget" data-unavailable="<%= @item.unavailable_dates.to_json %>"></p>

  <%= simple_form_for [ @item, @booking ] do |f| %>
    <div class="form-row align-items-center">
      <div class="col-3 my-0">
        <%= f.input :start_date, as: :string, input_html: { id: 'start_date', class: 'my-0' }, label: false, placeholder: 'From' %>
      </div>
      <div class="col-3 my-0">
        <%= f.input :end_date, as: :string, input_html: { id: 'end_date', class: 'my-0' }, label: false, placeholder: 'To' %>
      </div>
      <div class="col-3 my-0">
        <%= f.submit "Book", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <p class="my-3">Your total for those dates is $<span id="calc-price"></span></p>

  <h4 class="my-3">Bookings:</h4>
  <% @bookings.each do |booking| %>
    <p>From: <%= booking.start_date %> to <%= booking.end_date %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<% @items.each do |item| %>
  <p>Book this item: <%= link_to item.name, item_path(item) %></p>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>